CREATE TABLE IF NOT EXISTS users(
  userid SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  role VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profile_pictures(
  profile_picture_id SERIAL PRIMARY KEY,
  userid INTEGER UNIQUE NOT NULL,
  data BYTEA NOT NULL,
  FOREIGN KEY (userid) REFERENCES users ON DELETE CASCADE
);
